### ISSUE TITLE
Error after 'Send Message' on Contact Us page

### ISSUE THREAD

**Issue by Rjpaine** [rockreyad/takenote#50]
**Describe the bug**

**To Reproduce**
Complete the 'Contact Us' form and press 'Send Message'

**Expected behavior**
a simple message saying 'Message Sent' should be displayed

**Screenshots**
![image](https://github.com/TakeNoteAI/takenote/assets/123137313/73aa4acd-e649-489a-a0ac-5ee40eded64a)

**Comment by rockreyad** [comment]
#68
